import type { Metadata } from "next";

/**
 * Every search and share string on the site, in one file.
 *
 * Two sets per page, because they are read in two different places:
 *
 *   title / description   what Google shows. Leads with the name someone would
 *                         type, and stays inside Google's budget.
 *   ogTitle / ogDescription   the card when the link is pasted into LinkedIn,
 *                         Slack or iMessage. Read by one person who already
 *                         clicked, so it can keep the page's own hook.
 *
 * The case study headlines stay on the pages untouched. Two of them ran to 90
 * and 103 characters, which Google cut mid-phrase; those hooks now live on the
 * cards, where a whole sentence belongs.
 */
export type PageSeo = {
  /** Search result title. Google truncates near 60 characters. */
  title: string;
  /** Search result description. Google truncates near 160. */
  description: string;
  ogTitle: string;
  ogDescription: string;
  /** 1200x630, generated by scripts/og-images.mjs. Omit for no card image. */
  ogImage?: string;
};

export const PAGE_SEO: Record<string, PageSeo> = {
  "/": {
    title: "Stephen Aguila — Product Designer", // 33
    description:
      "Product designer with ten years across editorial, regulated sports betting and B2B software. I design and ship, so decisions get answered in production.", // 152
    ogTitle: "Stephen Aguila, a product designer who ships",
    ogDescription:
      "Ten years of product design across editorial, regulated sports betting and B2B software. Case studies on making buried features impossible to miss.",
    // Homepage card image comes later, by request.
  },

  "/exploration": {
    title: "Side Projects and Photography — Stephen Aguila", // 46
    description:
      "A floating gallery of personal work: travel photography, generated imagery, branding studies and one-off digital experiments across mediums.", // 140
    ogTitle: "My creative playground",
    ogDescription:
      "One-off digital projects, travel photography and branding experiments. The work that doesn't fit neatly into a case study.",
    // No image by request; this one shares as text.
  },

  "/work/wb-free-spins": {
    title: "WynnBET Free Spins Redesign — Stephen Aguila", // 44
    description:
      "Free spins were awarded, then lost without notice. A redesign that surfaced them everywhere players look and cut the support tickets asking where they went.", // 156
    ogTitle: "Free spins players were given, then lost",
    ogDescription:
      "Making them visible before they expire. A WynnBET casino redesign that took the spin out of the game that awarded it.",
    ogImage: "/og/wb-free-spins.jpg",
  },

  "/work/wb-leaderboards": {
    title: "WynnBET Leaderboards Redesign — Stephen Aguila", // 46
    description:
      "Leaderboard matches existed but sat buried in promotions. A dedicated page, direct opt-in and a live countdown, so players could find, join and follow them.", // 156
    ogTitle: "The competition was there. Finding it wasn't.",
    ogDescription:
      "Rethinking how WynnBET players discover, join and follow leaderboard matches.",
    ogImage: "/og/wb-leaderboards.jpg",
  },

  "/work/wb-sportsbook": {
    title: "WynnBET Sportsbook Redesign, 11 States — Stephen Aguila", // 55
    description:
      "A sportsbook and casino rebuilt for eleven states, each with its own legal restrictions, using modular components so one experience bends to every rulebook.", // 156
    ogTitle: "One sportsbook, eleven rulebooks",
    ogDescription:
      "The redesigned WynnBET platform across eleven states, each with its own legal restrictions.",
    ogImage: "/og/wb-sportsbook.jpg",
  },

  "/work/bingo-ai-job-matching-platform-for-seniors": {
    title: "Bingo AI, Job Matching for Retirees 65+ — Stephen Aguila", // 56
    description:
      "A voice-supported job matching platform for retirees 65+, designed for people that complex forms shut out. Winner of the first Innovation Jam Hackathon.", // 152
    ogTitle: "Flexible work for retirees 65+",
    ogDescription:
      "A voice-supported job matching platform, and the first-ever Innovation Jam Hackathon winner at Go Studio with InComm Payments.",
    ogImage: "/og/bingo-ai-job-matching-platform-for-seniors.jpg",
  },

  "/work/wrist-check-a-peer-to-peer-market-place": {
    title: "Wrist Check, a Luxury Watch Marketplace — Stephen Aguila", // 56
    description:
      "A peer-to-peer marketplace for luxury watches, built around authentication, seller reputation and buyer education in a market full of counterfeits.", // 148
    ogTitle: "40 million counterfeit Swiss watches are sold a year",
    ogDescription:
      "A peer-to-peer marketplace built around authenticity, seller reputation and buyer education.",
    ogImage: "/og/wrist-check-a-peer-to-peer-market-place.jpg",
  },
};

/**
 * The complete Metadata for a route.
 *
 * The openGraph block is spelled out in full every time on purpose. Next merges
 * metadata shallowly, so a page that sets even one openGraph field discards the
 * parent's entire block, siteName and url included. Assembling the whole object
 * here removes that failure mode rather than relying on inheritance that does
 * not happen.
 */
export function buildMetadata(route: string): Metadata {
  const seo = PAGE_SEO[route];
  if (!seo) return {};

  const isCaseStudy = route.startsWith("/work/");

  return {
    title: seo.title,
    description: seo.description,
    alternates: { canonical: route },
    openGraph: {
      title: seo.ogTitle,
      description: seo.ogDescription,
      url: route,
      siteName: "Stephen Aguila",
      locale: "en_US",
      type: isCaseStudy ? "article" : "website",
      // Relative paths resolve against metadataBase in the root layout.
      ...(seo.ogImage
        ? { images: [{ url: seo.ogImage, width: 1200, height: 630 }] }
        : {}),
    },
  };
}
